pipeline {
  agent any
  tools { go '1.23' }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Unit tests') {
      steps {
        sh 'go test'
      }
    }
    stage('Build') {
      steps {
        sh 'go build'
      }
    }
  }
}
